name: test

on:
  workflow_dispatch:

jobs:
  list-folders:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-folders.outputs.folders }}
    steps:
      - uses: actions/checkout@v2
      - id: set-folders
        run: echo "::set-output name=folders::$(cat folders.everdrift | jq -R -s -c 'split("\n")[:-1]')"
  check:
    needs: list-folders
    runs-on: ubuntu-latest
    strategy:
        matrix:
            folder: ${{ fromJson(needs.list-folders.outputs.matrix) }}
    steps: 
      - run: |
          echo "Deploying for folder: ${{ matrix.folder }}"



