name: test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    # Define a matrix with your folders
    strategy:
      matrix:
        folder: ${{ fromJson(env.FOLDER_LIST) }}
    env:
      FOLDER_LIST: ${{ vars.FOLDER_LIST }}
    steps:


      - name: Deploy for folder ${{ matrix.folder }}
        run: |
          echo "Deploying for folder: ${{ matrix.folder }}"
