name: test

on:
  workflow_dispatch:

jobs:

  list-folders:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-folders.outputs.folders }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3
      - id: set-folders
        run: echo "::set-output name=folders::$(cat folders.everdrift | jq -R -s -c 'split("\n")[:-1]')"

        
  everdrift:
    needs: list-folders
    runs-on: ubuntu-24.04
    strategy:
        matrix:
            folder: ${{ fromJson(needs.list-folders.outputs.matrix) }}
    steps: 
      - uses: actions/checkout@v2
      - run: |
          rootDir=`pwd`
          everdrift=$rootDir/everdrift.py
          cd ${{ matrix.folder }}
          pwd
          echo $everdrift
          python3 everdrift


  slack-notify:
    if: failure()
    needs: everdrift
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "TO DO"



