name: test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(env.FOLDER_LIST) }}
    env:
      FOLDER_LIST: ${{ vars.FOLDER_LIST }} 
    steps:

      - name: Deploy for folder ${{ matrix.folder }}
        run: |
          echo "Deploying for folder: ${{ matrix.folder }}"
