name: test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load folders from FOLDER_LIST
        id: load-folders
        run: |
          echo "matrix=$(echo '${{ vars.FOLDER_LIST }}' | tr '\n' ' ' | jq -R -s -c 'split(" ")')" >> $GITHUB_ENV

    strategy:
      matrix:
        folder: ${{ fromJson(env.matrix) }}
        
  deploy2:
    needs: deploy
    runs-on: ubuntu-latest
    steps:


      - name: Deploy for folder ${{ matrix.folder }}
        run: |
          echo "Deploying folder: ${{ matrix.folder }}"

