name: test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Define a matrix with your folders
    strategy:
      matrix:
        folder: [foo, bar] # Add folder names here
    steps:


      - name: Deploy for folder ${{ matrix.folder }}
        run: |
          echo "Deploying for folder: ${{ matrix.folder }}"
